CREATE TABLE MON
(
	MAMON CHAR(10) NOT NULL PRIMARY KEY,
	TENMON NVARCHAR(50),
	GIA MONEY
)

CREATE TABLE BAN
(
	MABAN CHAR(10) NOT NULL PRIMARY KEY,
	TENBAN NVARCHAR(50)
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50),
	CCCD CHAR(12),
	DIACHI NVARCHAR(100),
	SDT CHAR(10),
	NGAYSINH DATE,
	NGAYVAOLAM DATE,
	LUONG MONEY
)

CREATE TABLE PHANCONG
(
	MANV CHAR(10) NOT NULL PRIMARY KEY,
	CALAMVIEC CHAR(50),
	CONSTRAINT FK_PHANCONG_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE PHIEUCHI
(
	MAPHIEUCHI CHAR(10) NOT NULL PRIMARY KEY,
	MANV CHAR(10),
	NGAYCHI DATE,
	TONGTIENCHI MONEY,
	LYDOCHI NVARCHAR(100),
	CONSTRAINT FK_PHIEUCHI_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CHITIETPHIEUCHI
(
	MAPHIEUCHI CHAR(10) NOT NULL PRIMARY KEY,
	TIENCHI MONEY,
	CONSTRAINT FK_CHITIETPHIEUCHI_MAPHIEUCHI FOREIGN KEY (MAPHIEUCHI) REFERENCES PHIEUCHI(MAPHIEUCHI)
)

CREATE TABLE HOADON
(
	MAHD CHAR(10) NOT NULL PRIMARY KEY,
	MABAN CHAR(10),
	MANV CHAR(10),
	NGAYHD DATE,
	TONGTIEN MONEY,
	DATHANHTOAN CHAR(10),
	CONSTRAINT FK_HOADON_MABAN FOREIGN KEY (MABAN) REFERENCES BAN(MABAN),
	CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CHITIETHOADON
(
	MAHD CHAR(10) NOT NULL PRIMARY KEY,
	MAMON CHAR(10),
	DONGIA MONEY,
	SOLUONG INTEGER,
	CONSTRAINT FK_CHITIETHOADON_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETHOADON_MAMON FOREIGN KEY (MAMON) REFERENCES MON(MAMON)
)